package dev.cao.finch.ui

/**
 * 「大作信号」识别：内置知名系列/大厂/平台独占关键词，
 * 给发售日程条目打分排序，让大作顶到最前（不删小游戏，只是沉底）。
 * 名单是可扩展的，后续可再补。
 */
object MajorGameScorer {

    // 知名系列/游戏（中英）
    private val series = listOf(
        "最终幻想", "ff ", "ffxiv", "ff7", "ff16", "FF VII", "FF XVI",
        "勇者斗恶龙", "dragon quest",
        "怪物猎人", "monster hunter",
        "塞尔达", "zelda",
        "宝可梦", "pokemon", "pocket monsters",
        "马力欧", "mario", "马里奥",
        "星之卡比", "kirby",
        "splatoon", "斯普拉遁",
        "动物森友会", "animal crossing",
        "异度神剑", "xenoblade",
        "任天堂明星大乱斗", "smash bros",
        "王国之心", "kingdom hearts",
        "合金装备", "metal gear",
        "生化危机", "resident evil",
        "鬼泣", "devil may cry",
        "使命召唤", "call of duty",
        "战地", "battlefield",
        "刺客信条", "assassin's creed",
        "孤岛惊魂", "far cry",
        "看门狗", "watch dogs",
        "巫师", "the witcher",
        "赛博朋克", "cyberpunk",
        "艾尔登法环", "elden ring",
        "黑暗之魂", "dark souls",
        "只狼", "sekiro",
        "血源", "bloodborne",
        "战神", "god of war",
        "最后生还者", "last of us",
        "神秘海域", "uncharted",
        "地平线", "horizon zero dawn",
        "蜘蛛侠", "spider-man", "spiderman",
        "漫威", "marvel",
        "蝙蝠侠", "batman",
        "gta", "侠盗猎车",
        "荒野大镖客", "red dead",
        "古墓丽影", "tomb raider",
        "质量效应", "mass effect",
        "光环", "halo",
        "极限竞速", "forza",
        "战争机器", "gears of war",
        "地铁", "metro",
        "毁灭战士", "doom",
        "掠食", "prey",
        "星空", "starfield",
        "上古卷轴", "elder scrolls",
        "辐射", "fallout",
        "博德之门", "baldur",
        "神界", "divinity",
        "永恒之柱", "pillars of eternity",
        "暗黑破坏神", "diablo",
        "魔兽", "warcraft",
        "星际争霸", "starcraft",
        "英雄联盟", "league of legends",
        "valorant", "瓦罗兰特",
        "cs", "反恐精英", "counter-strike", "counter strike",
        "dota",
        "守望先锋", "overwatch",
        "堡垒之夜", "fortnite",
        "apex",
        "绝地求生", "pubg",
        "永劫无间", "naraka",
        "原神", "genshin",
        "崩坏", "honkai",
        "星穹铁道", "star rail",
        "绝区零", "zenless",
        "鸣潮", "wuthering",
        "明日方舟", "arknights",
        "碧蓝幻想", "granblue",
        "蔚蓝档案", "blue archive",
        "公主连结", "princess connect",
        "fate", "fgo", "命运-冠位",
        "尼尔", "nier",
        "如龙", "yakuza", "like a dragon",
        "审判之眼", "judgment",
        "女神异闻录", "persona",
        "真女神转生", "shin megami tensei",
        "轨迹", "trails of", "kiseki",
        "伊苏", "ys ",
        "传说系列", "tales of",
        "皇牌空战", "ace combat",
        "实况", "pro evolution", "e-football",
        "fifa", "fc 2", "ea sports fc",
        "nba 2k",
        "麦登", "madden",
        "如龙8", "dragon gaiden",
        "黑暗之魂2", "dark souls ii",
        "匹诺曹", "lies of p",
        "黑神话", "black myth", "wukong",
        "星球大战", "star wars",
        "指环王", "lord of the rings",
        "哈利波特", "harry potter",
        "侏罗纪", "jurassic",
        "异形", "alien",
        "终结者", "terminator",
        "变形金刚", "transformers",
        "忍者龙剑传", "ninja gaiden",
        "忍者神龟", "ninja turtles",
        "洛克人", "megaman", "rockman",
        "街霸", "street fighter",
        "拳皇", "king of fighters",
        "铁拳", "tekken",
        "格斗之王", "mortal kombat",
        "真人快打", "mortal kombat",
        "罪恶装备", "guilty gear",
        "苍翼默示录", "blazblue",
        "龙珠", "dragon ball",
        "火影忍者", "naruto",
        "海贼王", "one piece",
        "死神", "bleach",
        "我的世界", "minecraft",
        "泰拉瑞亚", "terraria",
        "星露谷", "stardew",
        "空洞骑士", "hollow knight",
        "死亡细胞", "dead cells",
        "杀戮尖塔", "slay the spire",
        "哈迪斯", "hades",
        "以撒", "isaac",
        "吸血鬼幸存者", "vampire survivors",
        "潜水员戴夫", "dave the diver",
        "赛博朋克2077", "cyberpunk 2077",
        "地平线西之绝境", "forbidden west",
        "死亡搁浅", "death stranding",
        "对马岛", "ghost of tsushima",
        "老头环", "elden ring",
        "装甲核心", "armored core",
        "艾尔登", "elden",
    )

    // 大厂/制作组（名字里带了就算大作信号）
    private val studios = listOf(
        "nintendo", "任天堂",
        "sony", "playstation", "圣莫尼卡",
        "microsoft", "xbox", "343", "任天堂",
        "fromsoftware", "from software", "万代南梦宫", "bandai namco",
        "capcom", "卡普空",
        "square enix", "史克威尔",
        "sega", "世嘉",
        "konami", "科乐美",
        "ubi", "ubisoft", "育碧",
        "ea ", "electronic arts", "艺电",
        "activision", "动视",
        "blizzard", "暴雪",
        "rockstar", "take-two",
        "bethesda", "贝塞斯达",
        "valve",
        "epic games",
        "cd projekt",
        "kojima", "小岛秀夫",
        "naughty dog", "顽皮狗",
        "insomniac",
        "guerrilla",
        "santa monica",
        "supermassive",
        "remedy",
        "techland",
        "dead by daylight", "Behaviour",
        "2k", "take two",
    )

    private val keywords = listOf(
        "remake", "reboot", "重制",
        "definitive", "完全版",
        "collection", "合集",
        "anniversary", "周年",
        "deluxe", "豪华版", "终极版", "黄金版",
        "early access", "抢先体验",
    )

    /**
     * 打分：命中系列 +3、大厂 +2、关键词 +1；返回 >= 0 的分数
     * （英文会小写匹配，全名分段匹配防误伤）
     */
    fun score(name: String, nameCn: String?): Int {
        var s = 0
        val hay = (name + " " + (nameCn ?: "")).lowercase()
        for (k in series) if (hay.contains(k.lowercase())) s += 3
        for (k in studios) if (hay.contains(k.lowercase())) s += 2
        for (k in keywords) if (hay.contains(k.lowercase())) s += 1
        return s
    }
}